"""1_2_3_usernames

Revision ID: 29c621f49f8d
Revises: 
Create Date: 2020-07-24 17:44:37.483980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29c621f49f8d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('second_name', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('third_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'third_name')
    op.drop_column('user', 'second_name')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
